name: api-pr

on:
  pull_request:
    branches:
      - master
      - develop                         

jobs:
  build-api:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./api
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet 8
        id: dotnet-install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        id: dotnet-restore
        run: dotnet restore

      - name: Build
        id: dotnet-build
        run: dotnet build

      


  